### ISSUE TITLE
pytorch-lightning tests setup fails

### ISSUE THREAD

**Issue by cdeepali** [open-ce/pytorch-lightning-feedstock#8]
```
Collecting scikit-image>=0.17.2
  Downloading scikit-image-0.17.2.tar.gz (29.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/opence-conda-env-20201222073037/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8ahqxlg4/scikit-image_d936d631724d4dd3943573ea01596fb1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8ahqxlg4/scikit-image_d936d631724d4dd3943573ea01596fb1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g4lvt88_
         cwd: /tmp/pip-install-8ahqxlg4/scikit-image_d936d631724d4dd3943573ea01596fb1/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8ahqxlg4/scikit-image_d936d631724d4dd3943573ea01596fb1/setup.py", line 30, in <module>
        LONG_DESCRIPTION = f.read()
      File "/opt/conda/envs/opence-conda-env-20201222073037/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4029: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bnemanich** [comment]
One way to get around this is to install scikit-image through conda before doing the pip installs. That way, it won't try to actually build scikit-image. So, maybe something like this:
```
conda install scikit-image>=17.2
pip install -r requirements/test.txt
```

**Comment by cdeepali** [comment]
I have tried this already, but PyTorch uses `scikit-image 0.16`. So I need to rebuild the packages and check.
